# Identificación de Títulos Faltantes

Este notebook tiene como objetivo identificar los títulos de películas presentes en el dataset principal, utilizado para realizar el clustering, que aún no han sido scrapeados. Para ello, se compara un dataset con los títulos ya procesados contra otro que contiene los títulos agrupados por características de clúster, permitiendo planificar el scraping en batch. 

El resultado final es una lista de títulos faltantes que será utilizada posteriormente en el notebook de web scraping.

In [2]:
import pandas as pd
import numpy as np

In [15]:
# Data_cluster
df_clustered = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\df_clustered.csv",index_col=0)

# Batch
scrap_ultimo_1 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_1.csv")
scrap_ultimo_2 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_2.csv")
scrap_ultimo_3 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_3.csv")
scrap_ultimo_4 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_4.csv")
scrap_ultimo_5 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_5.csv")
scrap_ultimo_6 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_6.csv")
scrap_ultimo_7 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_7.csv")
scrap_ultimo_8 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_8.csv")
scrap_ultimo_9 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_9.csv")
scrap_ultimo_10 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_10.csv")
scrap_ultimo_11 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_11.csv")
scrap_ultimo_12 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_12.csv")
scrap_ultimo_13 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_13.csv")
scrap_ultimo_14 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_14.csv")
scrap_ultimo_15 = pd.read_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\scrap_ultimo_15.csv")

#### Concatenar los dataframes

In [4]:
tablon = pd.concat([scrap_ultimo_1,scrap_ultimo_2,scrap_ultimo_3,scrap_ultimo_4,
                    scrap_ultimo_5,scrap_ultimo_6,scrap_ultimo_7,scrap_ultimo_8,
                    scrap_ultimo_9,scrap_ultimo_10,scrap_ultimo_11,scrap_ultimo_12,scrap_ultimo_13,scrap_ultimo_14,scrap_ultimo_15],axis=0)

titulos_tablon = tablon["title"].unique()
tablon

,title,title_comment,comment
0,The Healing Powers of Dude,Great Family Show with Awesome Messages!,This is a wonderful family show! It tackles gr...
1,The Healing Powers of Dude,"Ignore the ""controversies"" and just enjoy the ...",I have a huge crush on Larisa Oleynik since ba...
2,The Healing Powers of Dude,Cute and lovable,"I'm 34 and do not have anxiety disorder, nor d..."
3,The Healing Powers of Dude,Fun show but inaccurate,So I do love the show but it is not accurate f...
4,The Healing Powers of Dude,I like the show but its inaccurate,Cute show but I don't like that Dude is an emo...
...,...,...,...
1275,On My Block,Finally a show acuratley representing youth cu...,From the way the kids speak to the background ...
1276,On My Block,Great show,The dialogue is natural and full of quick witt...
1277,On My Block,"Good TV Show with talented, young actors",This show has great potential! The scoring is ...
1278,On My Block,Total disappointment,The show started out great living on planet ea...
1279,On My Block,Frustrating watch,It's so frustrating to watch the characters ac...

In [5]:
# Borrar duplicados y mal scrapeados
tablon = tablon.dropna(subset=["title_comment", "comment"], how="all")
tablon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90919 entries, 0 to 1279
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          90919 non-null  object
 1   title_comment  90918 non-null  object
 2   comment        90919 non-null  object
dtypes: object(3)
memory usage: 2.8+ MB

### Lógica para obtener las películas faltan por scrapear.

In [6]:
# Convertir las columnas a conjuntos de títulos únicos
titulos_cluster = set(df_clustered["title"].unique())
titulos_tablon = set(tablon["title"].unique())

# Encontrar los títulos que están en df_clustered pero no en tablon
titulos_faltantes = titulos_cluster - titulos_tablon

# Crear un DataFrame con los títulos faltantes
titulos_no_scrapeados = pd.DataFrame(list(titulos_faltantes), columns=["title"])

titulos_no_scrapeados["title_comment"] = pd.NA
titulos_no_scrapeados["comment"] = pd.NA
titulos_no_scrapeados

                                     title title_comment comment
0                                    Alelí          <NA>    <NA>
1                     The House of Flowers          <NA>    <NA>
2                       Pucca: Love Recipe          <NA>    <NA>
3                                     NCIS          <NA>    <NA>
4                                   Narcos          <NA>    <NA>
..                                     ...           ...     ...
584  Chicken Soup for the Soul's Being Dad          <NA>    <NA>
585                                      H          <NA>    <NA>
586                                   Manu          <NA>    <NA>
587                             Mama Drama          <NA>    <NA>
588       Me Against You: Mr. S's Vendetta          <NA>    <NA>

[589 rows x 3 columns]

In [11]:
tablon = pd.concat([tablon,titulos_no_scrapeados],axis=0)

### Export_to_csv

In [12]:
# tablon.to_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\df_reseñas.csv")

In [9]:
# titulos_no_scrapeados.to_csv("C:\\Users\\Usuario\\Desktop\\Netflix\\Raw_data\\titulos_pendientes_scrapear_12.csv")